```{r evalue, cache=cacheon}

mod <- summary(coxph(formula(paste0("Surv(sos_outtime_hosphf, sos_out_deathhosphf == 'Yes') ~ ablation + ", paste(modvars, collapse = " + "))),
  data = pop
))

evalc <- evalue(HR(mod$conf.int[1, 1], rare = FALSE), lo = mod$conf.int[1, 3], hi = mod$conf.int[1, 4])

modm <- coxph(Surv(sos_outtime_hosphf, sos_out_deathhosphf == "Yes") ~ ablation + frailty(par, distribution = "gamma"),
  data = matchpop
)
se <- sqrt(modm$var)[1]

evalm <- evalue(HR(exp(modm$coefficients[1]), rare = FALSE),
  lo = exp(modm$coefficients[1] - global_z05 * se),
  hi = exp(modm$coefficients[1] + global_z05 * se)
)

oute <- bind_cols(c("Model estimates", "E-values"), as_tibble(fn(evalc, 2)), as_tibble(fn(evalm, 2)))
colnames(oute) <- c("", rep(c("RR*", "Lower CI", "Upper CI"), 2))

footnote(default_kable(oute,
  scale_down = F,
  font_size = 8,
  caption = "Residual confounding - E-value"
) %>% add_header_above(c(" " = 1, "Adjusted individual covariates" = 3, "Adjusted ps matched" = 3)),
symbol = "Approximate conversions of the HR to RR are applied, assuming a non-rare outcome"
)
```

```{r evalue2, cache=cacheon}
out <- tibble(Variable = rownames(mod$coefficients), or = paste0(
  fn(mod$conf.int[, 1], dig = 2),
  " (", fn(mod$conf.int[, 3], dig = 2),
  "-", fn(mod$conf.int[, 4], dig = 2), "), ",
  fn(mod$coef[, 5], dig = 3, p = TRUE)
))

colnames(out) <- c("Variable", "HR (95% CI), p-value")

default_kable(out,
  scale_down = F,
  font_size = 8,
  caption = "HR for variables included in the model (for comparison with the magnitude of the E-value)"
)
```
