```{r km, cache=cacheon}

kmfunc <- function(time, event, eventcr = NULL, eventname, yposplus = rep(0, 3)) {

  # cox for print
  ## crude
  cmod <- summary(coxph(formula(paste0("Surv(", time, ",", event, "=='Yes') ~ ablation")),
    data = pop
  ))
  cp <- paste0(
    fn(cmod$conf.int[1, 1], dig = 2),
    " (", fn(cmod$conf.int[1, 3], dig = 2),
    "-", fn(cmod$conf.int[1, 4], dig = 2), "), ",
    fn(cmod$coef[1, 5], dig = 3, p = TRUE)
  )

  ## adjusted
  mod <- coxme(formula(paste0("Surv(", time, ",", event, "=='Yes') ~ ablation + (1 | par)")),
    data = matchpop
  )

  se <- sqrt(vcov(mod)[1])

  ap <- paste0(
    fn(exp(mod$coefficients[1]), dig = 2),
    " (", fn(exp(mod$coefficients[1] - global_z05 * se), dig = 2),
    "-", fn(exp(mod$coefficients[1] + global_z05 * se), dig = 2), "), ",
    fn((1 - pnorm(abs(mod$coeff[1] / se))) * 2, dig = 3, p = TRUE)
  )

  # and the curves...
  fits <- survfit(formula(paste0("Surv(", time, ",", event, "=='Yes') ~ ablation")),
    data = pop
  ) # needed also for cuminc for n at risk
  fitsm <- survfit(formula(paste0("Surv(", time, ",", event, "=='Yes') ~ ablation")),
    data = matchpop
  ) # needed also for cuminc for n at risk

  if (!is.null(eventcr)) {
    fit <- cuminc(
      ftime = pop %>% pull(!!sym(time)),
      fstatus = pop %>% pull(!!sym(eventcr)),
      cencode = 0,
      group = pop %>% pull(ablation)
    )
    fitm <- cuminc(
      ftime = matchpop %>% pull(!!sym(time)),
      fstatus = matchpop %>% pull(!!sym(eventcr)),
      cencode = 0,
      group = matchpop %>% pull(ablation)
    )

    # c(bottom, left, top, right)
    par(mar = c(8, 7.3, 0.5, 4.7) + 0.1)

    plot(fit[1:2],
      ylab = eventname,
      col = global_kicols,
      wh = c(1110, 1110),
      xlim = c(0, 5 * 365),
      ylim = c(0, 1),
      xlab = "Years",
      axes = F,
      lwd = 3,
      lty = c(1, 2),
      xaxs = "i", yaxs = "i"
    )
    lines(fitm$`No 1`$time,
      fitm$`No 1`$est,
      col = global_kicols[3],
      lwd = 3,
      lty = 3
    )
  } else {
    # c(bottom, left, top, right)
    par(mar = c(8, 7.3, 0.5, 4.7) + 0.1)

    plots <- plot(fits,
      fun = "event",
      ylab = eventname,
      xscale = 365,
      yscale = 100,
      col = global_kicols,
      mark.time = FALSE,
      bty = "n",
      xlim = c(0, 5 * 365),
      ylim = c(0, 1),
      xlab = "Years",
      axes = F,
      lwd = 3,
      lty = c(1, 2),
      xaxs = "i", yaxs = "i"
    )
    lines(fitsm[1],
      fun = "event",
      xscale = 365,
      yscale = 100,
      col = global_kicols[3:4],
      mark.time = FALSE,
      conf.int = FALSE,
      lwd = 3,
      lty = c(3, 4),
      xaxs = "i", yaxs = "i"
    )
  }

  axis(2, seq(0, 1, 0.25), seq(0, 100, 25), las = 2)
  axis(1, at = seq(0, 5, 1) * 365, seq(0, 5, 1))

  if (!is.null(eventcr)) {
    ypos <- timepoints(fit[1:2], 364.5 * 5)$est
    yposm <- timepoints(fitm[1:2], 364.5 * 5)$est[1]
  } else {
    ypos <- 1 - summary(fits, 364.5 * 5)$surv
    yposm <- 1 - summary(fitsm, 364.5 * 5)$surv[1]
  }
  ypos <- c(ypos, yposm)

  ylabs <- bind_cols(
    ypos = c(ypos + yposplus),
    ytext = c("MT all", "Ablation", "MT matched")
  )

  mtext(
    side = 4,
    line = .2,
    at = ylabs$ypos,
    ylabs$ytext,
    las = 1
  )

  mtext("No. at risk", side = 1, line = 3, at = -590, adj = 0, cex = 1, font = 2)
  mtext("MT all", side = 1, line = 4, at = -590, adj = 0, cex = 1)
  mtext("Ablation all", side = 1, line = 5, at = -590, adj = 0, cex = 1)
  mtext("MT matched", side = 1, line = 6, at = -590, adj = 0, cex = 1)
  mtext("Ablation matched", side = 1, line = 7, at = -590, adj = 0, cex = 1)

  nrisk <- summary(fits, seq(0, 5, 1) * 365)$n.risk
  nriskm <- summary(fitsm, seq(0, 5, 1) * 365)$n.risk

  axis(1, at = seq(0, 5, 1) * 365, labels = nrisk[1:6], line = 3, tick = FALSE, cex.axis = 1)
  axis(1, at = seq(0, 5, 1) * 365, labels = nrisk[7:12], line = 4, tick = FALSE, cex.axis = 1)
  axis(1, at = seq(0, 5, 1) * 365, labels = nriskm[1:6], line = 5, tick = FALSE, cex.axis = 1)
  axis(1, at = seq(0, 5, 1) * 365, labels = nriskm[7:12], line = 6, tick = FALSE, cex.axis = 1)

  text(0, 0.90, "Crude:", pos = 4)
  text(0, 0.85, "Adjusted:", pos = 4)

  text(380, 0.95, "HR (95% CI), p-value", pos = 4)
  text(380, 0.90, cp, pos = 4)
  text(380, 0.85, ap, pos = 4)
}
```

```{r mcf, cache=cacheon}

mcffunc <- function(datarec, datarecmatch, event, eventname, yposplus = rep(0, 3)) {

  # neg bin for print
  ## crude
  mod <- summary(glm.nb(formula(paste0(event, " ~ ablation + offset(log(sos_outtime_death))")),
    data = pop %>% filter(sos_outtime_death > 0)
  ))

  cp <-
    paste0(
      fn(exp(mod$coefficients[2, 1]), dig = 2),
      " (", fn(exp(mod$coefficients[2, 1] - global_z05 * mod$coefficients[2, 2]), dig = 2),
      "-", fn(exp(mod$coefficients[2, 1] + global_z05 * mod$coefficients[2, 2]), dig = 2), "), ",
      fn(mod$coefficients[2, 4], dig = 3, p = TRUE)
    )

  ## adjusted match
  mod <- summary(lme4::glmer.nb(formula(paste0(event, " ~ ablation + (1 | par) + offset(log(sos_outtime_death))")),
    data = matchpop %>% filter(sos_outtime_death > 0)
  ))

  se <- sqrt(vcov(mod)[1])

  ap <- paste0(
    fn(exp(mod$coefficients[2, "Estimate"]), 2),
    " (",
    fn(exp(mod$coefficients[2, "Estimate"] - global_z05 * mod$coefficients[2, "Std. Error"]), 2),
    "-",
    fn(exp(mod$coefficients[2, "Estimate"] + global_z05 * mod$coefficients[2, "Std. Error"]), 2),
    "), ",
    fn(mod$coefficients[2, "Pr(>|z|)"], dig = 3, p = T)
  )

  # needed for n at risk
  fitsn <- survfit(Surv(sos_outtime_death, sos_out_death == "Yes") ~ ablation,
    data = pop
  )
  fitsmn <- survfit(Surv(sos_outtime_death, sos_out_death == "Yes") ~ ablation,
    data = matchpop
  )

  fits <- mcf(Recur(sos_outtime, LopNrablation, sos_out) ~ ablation, data = datarec)
  fitsm <- mcf(Recur(sos_outtime, LopNrablation, sos_out) ~ ablation, data = datarecmatch)

  # c(bottom, left, top, right)
  par(mar = c(8, 7.3, 0.5, 4.7) + 0.1)

  plot(fits@MCF$time[fits@MCF$ablation == "No"],
    fits@MCF$MCF[fits@MCF$ablation == "No"],
    type = "l",
    ylab = eventname,
    col = global_kicols[1],
    xlim = c(0, 5 * 365),
    ylim = c(0, 2),
    xlab = "Years",
    axes = F,
    lwd = 3,
    lty = 1,
    xaxs = "i", yaxs = "i"
  )

  lines(fits@MCF$time[fits@MCF$ablation == "Yes"],
    fits@MCF$MCF[fits@MCF$ablation == "Yes"],
    col = global_kicols[2],
    lwd = 3,
    lty = 2
  )

  lines(fitsm@MCF$time[fitsm@MCF$ablation == "No"],
    fitsm@MCF$MCF[fitsm@MCF$ablation == "No"],
    col = global_kicols[3],
    lwd = 3,
    lty = 3
  )

  axis(2, seq(0, 2, .5), seq(0, 200, 50), las = 2)
  axis(1, at = seq(0, 5, 1) * 365, seq(0, 5, 1))

  # all no, all yes, no match
  ypos <- c(
    last(fits@MCF$MCF[fits@MCF$time <= 365 * 5 & fits@MCF$ablation == "No"]),
    last(fits@MCF$MCF[fits@MCF$time <= 365 * 5 & fits@MCF$ablation == "Yes"]),
    last(fitsm@MCF$MCF[fitsm@MCF$time <= 365 * 5 & fitsm@MCF$ablation == "No"])
  )

  ylabs <- bind_cols(
    ypos = c(ypos + yposplus),
    ytext = c("MT all", "Ablation", "MT matched")
  )

  mtext(
    side = 4,
    line = .2,
    at = ylabs$ypos,
    ylabs$ytext,
    las = 1
  )

  mtext("No. at risk", side = 1, line = 3, at = -590, adj = 0, cex = 1, font = 2)
  mtext("MT all", side = 1, line = 4, at = -590, adj = 0, cex = 1)
  mtext("Ablation all", side = 1, line = 5, at = -590, adj = 0, cex = 1)
  mtext("MT matched", side = 1, line = 6, at = -590, adj = 0, cex = 1)
  mtext("Ablation matched", side = 1, line = 7, at = -590, adj = 0, cex = 1)

  nrisk <- summary(fitsn, seq(0, 5, 1) * 365)$n.risk
  nriskm <- summary(fitsmn, seq(0, 5, 1) * 365)$n.risk

  axis(1, at = seq(0, 5, 1) * 365, labels = nrisk[1:6], line = 3, tick = FALSE, cex.axis = 1)
  axis(1, at = seq(0, 5, 1) * 365, labels = nrisk[7:12], line = 4, tick = FALSE, cex.axis = 1)
  axis(1, at = seq(0, 5, 1) * 365, labels = nriskm[1:6], line = 5, tick = FALSE, cex.axis = 1)
  axis(1, at = seq(0, 5, 1) * 365, labels = nriskm[7:12], line = 6, tick = FALSE, cex.axis = 1)

  text(0, 1.80, "Crude:", pos = 4)
  text(0, 1.70, "Adjusted:", pos = 4)

  text(380, 1.90, "IRR (95% CI), p-value", pos = 4)
  text(380, 1.80, cp, pos = 4)
  text(380, 1.70, ap, pos = 4)
}
```

```{r kmdeathhosphf, fig.cap="All-cause mortality/first HF hospitalization", cache=cacheon, dependson="km"}
kmfunc(
  time = "sos_outtime_hosphf",
  event = "sos_out_deathhosphf",
  eventname = "All-cause mortality/first HF hospitalization (%)",
  yposplus = c(0, 0, 0)
)
```

```{r kmdeath, fig.cap="All-cause mortality", cache=cacheon, dependson="km"}
kmfunc(
  time = "sos_outtime_death",
  event = "sos_out_death",
  eventname = "All-cause mortality (%)",
  yposplus = c(0, 0, 0)
)
```

```{r kmhosphf, fig.cap="First HF hospitalization", cache=cacheon, dependson="km"}
kmfunc(
  time = "sos_outtime_hosphf",
  event = "sos_out_hosphf",
  eventcr = "sos_out_hosphf_cr",
  eventname = "First HF hospitalization (%)",
  yposplus = c(0.005, 0, -0.005)
)
```

```{r kmrechosphf, fig.cap="Recurent HF hospitalization", cache=cacheon, dependson="mcf"}
mcffunc(
  datarec = pop_rec_hosphf,
  datarecmatch = matchpop_rec_hosphf,
  event = "sos_out_nohosphf",
  eventname = "Cumulative mean of HF hospitalizations (per 100 patients)",
  yposplus = c(0.025, -0.025, 0)
)
```

```{r kmhospstroketia, fig.cap="First TIA/Stroke hospitalization", cache=cacheon, dependson="km"}
kmfunc(
  time = "sos_outtime_hospstroketia",
  event = "sos_out_hospstroketia",
  eventcr = "sos_out_hospstroketia_cr",
  eventname = "First TIA/Stroke hospitalization (%)",
  yposplus = c(0, -0.01, 0.01) # no all, yes, no matched
)
```

```{r kmdeathcv, fig.cap="CV mortality", cache=cacheon, dependson="km"}
kmfunc(
  time = "sos_outtime_death",
  event = "sos_out_deathcv",
  eventcr = "sos_out_deathcv_cr",
  eventname = "CV mortality (%)",
  yposplus = c(0, 0, 0) # no all, yes, no matched
)
```

```{r kmhospcv, fig.cap="First CV hospitalization", cache=cacheon, dependson="km"}
kmfunc(
  time = "sos_outtime_hospcv",
  event = "sos_out_hospcv",
  eventcr = "sos_out_hospcv_cr",
  eventname = "First CV hospitalization (%)",
  yposplus = c(-0.005, 0, 0.005) # no all, yes, no matched
)
```

```{r kmhospany, fig.cap="First hospitalization", cache=cacheon, dependson="km"}
kmfunc(
  time = "sos_outtime_hospany",
  event = "sos_out_hospany",
  eventcr = "sos_out_hospany_cr",
  eventname = "First hospitalization (%)",
  yposplus = c(0, 0, 0)
)
```
